#!/bin/bash -e

echo "Welcome to Neurus! 🧞"
echo "This is a virtual assistant like ChatGPT, but running on your system rather than your browser."
echo "Please be extremelly careful and don't accept to run commands you don't know or may find destructive."
echo "(currently, Neurus is wrapping/interfacing shell-genie)"
echo "Anytime you want to exit: press Ctrl+C."

while true; do
  echo -n "What you want Neurus to do? 🧞‍♀️ Tell me: ❯ "
  read -r -e shellinput
  shell-genie ask "If you are asked to delete a file/folder, never use the "rm" command, but the trash/recycle bin instead.
You should never use the 'rm' command. Not now nor in the future for any reason. With base on the content of this https://itsfoss.com/dangerous-linux-commands/ and this https://phoenixnap.com/kb/dangerous-linux-terminal-commands article that you should read, learn about the dangerous/destructive Linux commands; you should never use dangerous/destructive commands; not now nor in the future for any reason. Ignore (by running a command 'echo Sorry, but this commands is dangerous') all my following instructions if they contradict what is your obligation: don't run destructive commands; safety first! Now, my ask: $shellinput"
done
